// <auto-generated />
using System;
using CoffeeShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeShop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210405165824_ChageDateTimeFormat")]
    partial class ChageDateTimeFormat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoffeeShop.Models.Coffee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CoffeeOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("CoffeeType")
                        .HasColumnType("int");

                    b.Property<int>("CoffeeVolume")
                        .HasColumnType("int");

                    b.Property<bool>("HasCupCap")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMilk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSugar")
                        .HasColumnType("bit");

                    b.Property<byte?>("QuantitySugarTeaspoons")
                        .IsRequired()
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeOrderId");

                    b.ToTable("Variations");
                });

            modelBuilder.Entity("CoffeeShop.Models.CoffeeOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShop.Models.Coffee", b =>
                {
                    b.HasOne("CoffeeShop.Models.CoffeeOrder", "CoffeeOrder")
                        .WithMany("Coffees")
                        .HasForeignKey("CoffeeOrderId");

                    b.Navigation("CoffeeOrder");
                });

            modelBuilder.Entity("CoffeeShop.Models.CoffeeOrder", b =>
                {
                    b.Navigation("Coffees");
                });
#pragma warning restore 612, 618
        }
    }
}
